<!-- Numpy Array  -->

scaler = data without dimesniosn  a=10  
vectore = data with dimension 

In [1]:
import numpy as np 

In [3]:
['asfd',2,3,4]

['asfd', 2, 3, 4]

In [2]:
np.array(['asfd',2,3,4])

array(['asfd', '2', '3', '4'], dtype='<U4')

In [4]:
type(np.array(['asfd',2,3,4]))

numpy.ndarray

In [5]:
#upcasting

In [6]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [8]:
np.array([1,2,3,3.4])

array([1. , 2. , 3. , 3.4])

In [9]:
# two dimnesion 

np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [12]:
np.array([[1,2],[3,4]], ndmin = 4)

array([[[[1, 2],
         [3, 4]]]])

In [11]:
# minimum dimension :2

np.array([1,2,3,4,5], ndmin=5)

array([[[[[1, 2, 3, 4, 5]]]]])

In [15]:
# for convert intire data into given data type 
np.array([1,2,3,4,5.7], dtype = complex)

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.7+0.j])

In [16]:
np.array([1,2,3,4,5], dtype = int)

array([1, 2, 3, 4, 5])

In [17]:
np.array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.7+0.j], dtype=int)

TypeError: can't convert complex to int

In [18]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [19]:
np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [20]:
x = np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [22]:
np.array([(1,2),(3,4)])

array([[1, 2],
       [3, 4]])

In [21]:
x[1][0]

3

In [23]:
type(x[1][0])  #i8 means 16bit and i4 meand 32bit

numpy.int16

In [24]:
x[0][1]

2

In [25]:
type(x[0][1])

numpy.int64

In [26]:
type(x[0][0])  #i2 means int 64bit representation

numpy.int16

In [31]:
x= np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','<i8')])
type(x[0][0])

numpy.int16

In [32]:
x= np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<i8')])
type(x[0][1])

numpy.int64

In [33]:
x= np.array([(1,2),(3,4)], dtype=[('a','<i8'),('b','<i8')])
type(x[0][0])

numpy.int64

In [34]:
x= np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<i8')])
type(x[0][0])

numpy.int32

In [38]:
x= np.array([(1,2),(3,4)], dtype=[('a','<i8'),('b','<i2')])
type(x[0][1]),type(x[1][1])

(numpy.int16, numpy.int16)

In [30]:
type(x)

numpy.ndarray

In [39]:
# creating an array from subclass ,,, matrix is suset of array


np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [41]:
np.mat([[1,2],[3,4]])

matrix([[1, 2],
        [3, 4]])

In [44]:
# Matrix

In [40]:
type(np.mat([[1,2],[3,4]]))

numpy.matrix

In [42]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [43]:
np.mat([[1,2],[3,4],[5,6,7]])

matrix([[list([1, 2]), list([3, 4]), list([5, 6, 7])]], dtype=object)

# nimpy.asarray()

convert the input to an array 

convert a list into an array

In [45]:
a=[1,2]
type(a)

list

In [46]:
np.asarray(a)

array([1, 2])

In [48]:
a = np.asarray((1,2))
a

array([1, 2])

In [49]:
a = np.asarray((1,2), dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [50]:
issubclass(np.matrix, np.ndarray)

True

In [51]:
issubclass(np.ndarray, np.matrix)

False

# numpy.asanyarray()`

In [52]:
a =[1,2]
np.asanyarray(a)  #covert if dtaa in  non array formate 

array([1, 2])

In [53]:
type(np.asanyarray(a) )

numpy.ndarray

In [54]:
a = np.matrix([1,2])
a

matrix([[1, 2]])

In [55]:
np.asanyarray(a)  #it is not conerting the data into array

matrix([[1, 2]])

In [56]:
np.array(a)  #array() convert the matrix into array 

array([[1, 2]])

In [57]:
np.asarray(a) #asarray() also convert the matrix into array 

array([[1, 2]])

In [58]:
np.asanyarray(a)  #asanaray() not coverting the matrix into array
# bcs matrix is subclass od an array 

matrix([[1, 2]])

### Copy 
2. deep copy
1. swallow copy

In [59]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [60]:
y = x  #y wil create a refrence wit x  not create a new storage 
#both are pointing to the same elocation 

In [61]:
y

array([1, 2, 3])

In [62]:
y[1],x[1]

(2, 2)

In [63]:
y[1]=123
y

array([  1, 123,   3])

In [64]:
x  #same will reflect in x also 

array([  1, 123,   3])

In [65]:
x[0] = 234423

In [66]:
x

array([234423,    123,      3])

In [67]:
y

array([234423,    123,      3])

In [68]:
x[0],y[0]  #both will try to point same location 

(234423, 234423)

In [69]:
x

array([234423,    123,      3])

### Deep Copy 
1. cerate a new space

In [74]:
z = np.copy(x)  # it will copy a data to z abd point some another location also 

In [75]:
z

array([234423,    123,      3])

In [76]:
# both will never point a same location 
z[0]

234423

In [77]:
z[0]=32

In [78]:
z

array([ 32, 123,   3])

In [79]:
x  #x will not showing the changes  in z 
# so we can say x point another location and z other location 

array([234423,    123,      3])

### Numpy Function 
genetrae a array with condidtion 

In [80]:
np.fromfunction(lambda i,j : i==j, (3,3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [81]:
np.fromfunction(lambda i,j : i*j, (3,3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [82]:
np.fromfunction(lambda i,j,k : i*j*k, (3,3,3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [83]:
np.fromfunction(lambda i,j,k,l : i*j*k*l, (3,3,3,3), dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [84]:
np.fromfunction(lambda i,j,k,l : i*j*k*l, (10,3,3,3), dtype=int)

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  3,  6],
         [ 0,  6, 12]],

        [[ 0,  0,  0],
         [ 0,  6, 12],
         [ 0, 12, 24]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]],

In [85]:
np.fromfunction(lambda i,j,k,l : i*j*k*l, (1,3,3,3), dtype=int)

array([[[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]]])

In [86]:
# create a new 1 d array from an iterable object 

In [96]:
iterable = [x*x for x in range(5)]
iterable

[0, 1, 4, 9, 16]

In [91]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [97]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [101]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001ED9775FE60>

In [99]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [102]:
np.fromiter(iterable, int)

array([ 0,  1,  4,  9, 16])

In [104]:
a = np.fromstring('1 2', sep=' ')
a

array([1., 2.])

In [105]:
a = np.fromstring('1 2',dtype= int,  sep=' ')
a

array([1, 2])

In [106]:
x1 = np.array([1,2,3,4])

In [107]:
x2 = np.array(['a','dd','dasd','12'])

In [108]:
x3 = np.array([1.1,2.1,3.1,4.1])


In [109]:
x4 = np.array([1.1,2,3,4.4])

In [111]:
r = np.core.records.fromarrays([x1,x2,x3,x4])
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2.1, 2. ), (3, 'dasd', 3.1, 3. ),
           (4, '12', 4.1, 4.4)],
          dtype=[('f0', '<i4'), ('f1', '<U4'), ('f2', '<f8'), ('f3', '<f8')])

In [112]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names = 'a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2.1, 2. ), (3, 'dasd', 3.1, 3. ),
           (4, '12', 4.1, 4.4)],
          dtype=[('a', '<i4'), ('b', '<U4'), ('c', '<f8'), ('d', '<f8')])

In [113]:
r[1]

(2, 'dd', 2.1, 2.)

In [115]:
r[0][1]

'a'

In [116]:
r[1]['a']

2

In [117]:
# data Types 

In [118]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)

In [119]:
type(arr)

numpy.ndarray

In [120]:
arr

array([1, 2, 3])

In [121]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
type(mat)

numpy.ndarray

In [122]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
mat.ndim

2

In [127]:
mat.size

9

In [128]:
mat.shape

(3, 3)

In [129]:
mat.dtype

dtype('int32')

In [130]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
type(mat)

numpy.ndarray

In [131]:
mat.dtype

dtype('float64')


# arange and linspace

In [132]:
range(4,7)

range(4, 7)

In [134]:
list(range(4,7))

[4, 5, 6]

In [135]:
list(range(4.4, 50,2))  #not allow float number if we talk about renge fun()

TypeError: 'float' object cannot be interpreted as an integer

In [137]:
list(range(40, 50,2))

[40, 42, 44, 46, 48]

In [138]:
np.arange(5,16)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [140]:
np.arange(5.6,11.3,2)

array([5.6, 7.6, 9.6])

In [141]:
np.arange(5,12.12,.12)

array([ 5.  ,  5.12,  5.24,  5.36,  5.48,  5.6 ,  5.72,  5.84,  5.96,
        6.08,  6.2 ,  6.32,  6.44,  6.56,  6.68,  6.8 ,  6.92,  7.04,
        7.16,  7.28,  7.4 ,  7.52,  7.64,  7.76,  7.88,  8.  ,  8.12,
        8.24,  8.36,  8.48,  8.6 ,  8.72,  8.84,  8.96,  9.08,  9.2 ,
        9.32,  9.44,  9.56,  9.68,  9.8 ,  9.92, 10.04, 10.16, 10.28,
       10.4 , 10.52, 10.64, 10.76, 10.88, 11.  , 11.12, 11.24, 11.36,
       11.48, 11.6 , 11.72, 11.84, 11.96, 12.08])

In [143]:
np.arange(16,0,-2)

array([16, 14, 12, 10,  8,  6,  4,  2])

In [145]:
np.linspace(1,10,5)  #start end and no. of data

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [146]:
np.linspace(1,5,10)  #considring upper bound

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [147]:
np.linspace(1,5,10, endpoint=False)

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6])

In [148]:
np.linspace(1,5,10, endpoint=True)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

# Matrux Creation 

In [149]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [150]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [154]:
np.zeros((3,4,2)) #(z,x,y)

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [155]:
np.ones(2)

array([1., 1.])

In [156]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [157]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [158]:
5 + np.ones((3,5))  #data manupilation

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [159]:
5.45 + np.ones((3,5))

array([[6.45, 6.45, 6.45, 6.45, 6.45],
       [6.45, 6.45, 6.45, 6.45, 6.45],
       [6.45, 6.45, 6.45, 6.45, 6.45]])

In [160]:
np.ones((3,5)) + 7.777

array([[8.777, 8.777, 8.777, 8.777, 8.777],
       [8.777, 8.777, 8.777, 8.777, 8.777],
       [8.777, 8.777, 8.777, 8.777, 8.777]])

In [161]:
np.ones((3,5))*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [163]:
np.empty((3,5)) # it craetes same instance from previous one 

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [164]:
mat1 = np.eye(4)  #identitiy matrix 
mat1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [165]:
type(mat1)

numpy.ndarray

In [166]:
mat1 = np.eye(5)  #identitiy matrix 
mat1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [167]:
np.arange(4)

array([0, 1, 2, 3])

In [168]:
np.linspace(2.0,5.0, num=4)

array([2., 3., 4., 5.])

In [169]:
np.linspace(2.0,5.0, num=4, endpoint=False)

array([2.  , 2.75, 3.5 , 4.25])

In [170]:
np.linspace(2.0,5.0, num=4, endpoint=False, retstep=True)

(array([2.  , 2.75, 3.5 , 4.25]), 0.75)

In [171]:
np.linspace(2.0,5.0, num=10, endpoint=False, retstep=True)

(array([2. , 2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7]), 0.3)

In [172]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [173]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [176]:
np.logspace(2.0, 3.0, num=4, endpoint=False, base=2)

array([4.        , 4.75682846, 5.65685425, 6.72717132])

In [177]:
np.logspace(2.0, 3.0, num=4, endpoint=False, base=4)

array([16.      , 22.627417, 32.      , 45.254834])