In [2]:
import numpy as np
import pandas as pd

In [4]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
np.arange(16).ndim

1

In [6]:
np.arange(16).shape

(16,)

In [7]:
np.arange(16).reshape(4,4)  #2x8,8x2,16x1,1x16,4x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
x = np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
x = np.arange(16).reshape((8,2,1))
x

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [12]:
x = np.arange(16).reshape((8,2,1,1))
x

array([[[[ 0]],

        [[ 1]]],


       [[[ 2]],

        [[ 3]]],


       [[[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]]],


       [[[ 8]],

        [[ 9]]],


       [[[10]],

        [[11]]],


       [[[12]],

        [[13]]],


       [[[14]],

        [[15]]]])

In [14]:
x = np.arange(16).reshape((8,3)) #i need 24 data for perform this 
x

ValueError: cannot reshape array of size 16 into shape (8,3)

In [17]:
np.arange(16).reshape((1,-1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
np.arange(16).reshape((-1,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [22]:
x = np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
x = np.arange(16).reshape((4,-1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
x = np.arange(16).reshape((4,-12344))#u can use any ngative number 
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
x = np.arange(16).reshape((8,-12344))#u can use any ngative number 
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [25]:
x = np.arange(16).reshape((8,-12344,1))#u can use any ngative number 
x

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [27]:
x = np.arange(16).reshape((4,-1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
np.diag(x)

array([ 0,  5, 10, 15])

In [29]:
np.diag(x, k = -1)

array([ 4,  9, 14])

In [30]:
np.diag(x, k = 1)  #considering square afrer living one col

array([ 1,  6, 11])

In [32]:
x = np.arange(16).reshape((-1,8))
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [33]:
np.diag(x,k=1)

array([ 1, 10])

In [34]:
np.diag(x, k=-1)

array([8])

In [35]:
np.diag(x, k=-2)

array([], dtype=int32)

In [36]:
np.diag(x,k=0)

array([0, 9])

In [39]:
x = np.arange(16).reshape((4,-1))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.diag(np.diag(x, k=0))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [41]:
np.diag(np.diag(x, k=1))

array([[ 1,  0,  0],
       [ 0,  6,  0],
       [ 0,  0, 11]])

In [42]:
np.diag(np.diag(x, k=-1))

array([[ 4,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 14]])

In [43]:
np.diagflat([[1,2],[3,4]])  #faltten list and create a matrix as a diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
np.diagflat([[1,2],[3,4]], k=1) 

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [45]:
np.diagflat([[1,2],[3,4]], k=-1) 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
# An array with ones at below tye given diagonal and zeros elsewhere

In [48]:
np.tri(3,3,0, dtype=int)  #3x3 matrix and k=0

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

In [49]:
np.tri(3,5,0, dtype=int)  #3x3 matrix and k=0

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [50]:
np.tri(3,3,1, dtype=int) 

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [51]:
np.tri(3,3,-1, dtype=int) 

array([[0, 0, 0],
       [1, 0, 0],
       [1, 1, 0]])

In [52]:
np.tri(3,3,2, dtype=int) 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
np.tri(5,5,2, dtype=int) 

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [54]:
np.tri(5,5,1, dtype=int) 

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
np.tri(5,7,1, dtype=int) 

array([[1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 0]])

In [57]:
a  = np.tri(5,7,1, dtype=int) 
a

array([[1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 0]])

In [58]:
a[0]

array([1, 1, 0, 0, 0, 0, 0])

In [59]:
a[0][1]

1

In [61]:
a = np.tri(5,7,1, dtype=int) 
for i in a:
    print (i)
    

[1 1 0 0 0 0 0]
[1 1 1 0 0 0 0]
[1 1 1 1 0 0 0]
[1 1 1 1 1 0 0]
[1 1 1 1 1 1 0]


In [62]:
a = np.tri(5,7,1, dtype=int) 
for i in a:
    for j in i:
        print(j)

1
1
0
0
0
0
0
1
1
1
0
0
0
0
1
1
1
1
0
0
0
1
1
1
1
1
0
0
1
1
1
1
1
1
0


return a lower traingle of any array

In [64]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
np.tril(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [63]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [65]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], -1)

array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [69]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

In [70]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

# Random numer Generation 

In [73]:
np.random.rand(2,3)  #2x3 matrix random number for  0 to 1 (generate umniform distribited data btw 0 to 1)

array([[0.2759576 , 0.36235164, 0.91745335],
       [0.46843338, 0.47347686, 0.65204981]])

In [74]:
np.random.rand(2,3,8)

array([[[0.28582824, 0.36879531, 0.50270629, 0.41643512, 0.45398298,
         0.11783576, 0.32554432, 0.02838991],
        [0.35024444, 0.91679062, 0.94348779, 0.58357258, 0.07776326,
         0.72269861, 0.9847612 , 0.24761786],
        [0.40787508, 0.20119841, 0.25612426, 0.28824081, 0.51130398,
         0.80447127, 0.07920959, 0.7567811 ]],

       [[0.98553459, 0.0608156 , 0.37753226, 0.31441854, 0.34540844,
         0.35238899, 0.3382446 , 0.87578454],
        [0.16729476, 0.36443274, 0.02636877, 0.74885093, 0.41118913,
         0.6532483 , 0.93265089, 0.61827722],
        [0.34492768, 0.61884614, 0.65802338, 0.25760547, 0.37785948,
         0.14263646, 0.72988482, 0.43520133]]])

In [75]:
np.random.randn(4,3)  #generate std normal distributed data 

array([[ 0.3979613 , -0.56059789, -1.34491647],
       [ 0.82612691, -1.649744  , -0.15624043],
       [ 1.61057194, -0.52501968,  0.59056331],
       [-0.16877849,  0.53292524, -0.20594223]])

In [78]:
np.random.randn(4,3,3)


array([[[ 0.97927813, -0.59924715,  0.86164334],
        [ 1.76499554,  0.09623384, -0.16404994],
        [-0.23271206, -1.33072171, -0.68117164]],

       [[ 0.24702664,  2.25540268, -2.82039694],
        [-0.86103703, -0.20839287, -0.20933748],
        [-0.84423129,  0.42332666,  0.28247024]],

       [[ 1.70564353, -0.31666453,  2.76005975],
        [-1.03122286, -0.62023   ,  0.20916112],
        [-1.28855291,  0.97907973, -0.30739074]],

       [[-0.90422001,  0.35478498, -0.44785634],
        [-0.31071625,  0.23501376,  0.15648816],
        [-0.42605385,  1.81937806,  1.45103346]]])

In [81]:
np.random.randint(1,10)

5

In [83]:
np.random.randint(1,100,(4,4))

array([[74, 66, 26, 22],
       [80, 13, 31, 73],
       [36, 81, 57, 71],
       [34,  5, 89, 61]])

In [84]:
np.random.randint(1,100,(4,4,5))

array([[[40,  8, 17, 94, 54],
        [ 1, 81, 11, 46, 63],
        [61, 24, 41, 17, 13],
        [ 2, 42, 11, 59, 48]],

       [[ 1, 97, 46, 90, 74],
        [38,  8, 14, 18, 76],
        [ 5, 49, 41, 69, 24],
        [ 9, 70, 28, 87, 33]],

       [[42, 62, 44,  6, 12],
        [74, 72, 91,  8, 59],
        [82,  2, 16, 59, 53],
        [ 6, 89, 76, 43, 75]],

       [[57, 83, 60, 57, 65],
        [35, 68, 53, 79, 46],
        [89, 78, 30, 58, 50],
        [78, 58, 99, 62, 92]]])

# Reshaping 

In [87]:
from numpy.random import randint  as ri 
a = ri(1,100,30)
a

array([66, 10, 85, 21, 82, 82, 86, 50, 37, 38, 19, 97, 38, 17, 55, 46, 33,
       12, 71, 55, 39, 46, 53, 62, 66, 56, 27, 34, 56, 64])

In [91]:
b = a.reshape(2,3,5)
b

array([[[66, 10, 85, 21, 82],
        [82, 86, 50, 37, 38],
        [19, 97, 38, 17, 55]],

       [[46, 33, 12, 71, 55],
        [39, 46, 53, 62, 66],
        [56, 27, 34, 56, 64]]])

In [89]:
c = a.reshape(6,-587983)

In [90]:
c

array([[66, 10, 85, 21, 82],
       [82, 86, 50, 37, 38],
       [19, 97, 38, 17, 55],
       [46, 33, 12, 71, 55],
       [39, 46, 53, 62, 66],
       [56, 27, 34, 56, 64]])

In [92]:
A = ri(1,100,10)
A

array([91, 53, 61, 28, 96, 76, 34, 15, 98, 30])

In [93]:
np.sort(A)

array([15, 28, 30, 34, 53, 61, 76, 91, 96, 98])

In [95]:
M = ri(1,100,25).reshape(5,5)
M

array([[50, 79, 24, 93, 43],
       [80, 47, 99, 41, 60],
       [49,  6, 62, 99, 51],
       [84, 68, 61, 63, 31],
       [39, 34, 72, 22, 55]])

In [96]:
M = ri(1,100,(5,5))
M

array([[22, 43, 81, 96, 65],
       [77, 90, 40,  7, 21],
       [ 4, 98, 23, 86, 12],
       [87, 31, 64, 54, 86],
       [38, 58, 69, 54, 96]])

axis = 1(column), axsi=0(col wise) it is funda of pandas but here pretty much differ that is ..this 
axis=1 means movement of data during sorting as a column wise

axis=0 means movement of data during sorting as a row wiise 

it's not differ from pandas

In [97]:
np.sort(M, axis=1)   #movement of dta during sorting as col

array([[22, 43, 65, 81, 96],
       [ 7, 21, 40, 77, 90],
       [ 4, 12, 23, 86, 98],
       [31, 54, 64, 86, 87],
       [38, 54, 58, 69, 96]])

In [98]:
np.sort(M, axis=0)  #movement of dta aduring soirting as row

array([[ 4, 31, 23,  7, 12],
       [22, 43, 40, 54, 21],
       [38, 58, 64, 54, 65],
       [77, 90, 69, 86, 86],
       [87, 98, 81, 96, 96]])

In [101]:
M.max()

98

In [102]:
M.min()

4

In [110]:
M = ri(1,100,(5,5))
M

array([[17,  4,  2, 98, 24],
       [51,  5, 83, 84, 44],
       [49, 60, 12, 74, 79],
       [13, 25, 56, 32, 87],
       [57, 50, 15, 20, 32]])

In [105]:
print('Max of a location ', M.argmax(axis=1)) #compare with row and return col index 

Max of a location  [2 4 1 0 0]


In [111]:
print('Max of a location ', M.argmax(axis=0)) #compare with col and return rwo index

Max of a location  [4 2 1 0 3]


In [106]:
b = a.reshape(2,3,5)
b

array([[[66, 10, 85, 21, 82],
        [82, 86, 50, 37, 38],
        [19, 97, 38, 17, 55]],

       [[46, 33, 12, 71, 55],
        [39, 46, 53, 62, 66],
        [56, 27, 34, 56, 64]]])

In [108]:
print('Max of a location ', M.argmax()) #out of whole dataste 

Max of a location  20


In [107]:
print('Max of a location ', b.argmax())  #first flaten then return the max value index 

Max of a location  11


# Indexing and Slicing 

In [112]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [113]:
arr[7]

7

In [114]:
arr[3:6:2]

array([3, 5])

In [115]:
arr[-1:7:-1]

array([10,  9,  8])

In [116]:
arr[-1:-6:2]

array([], dtype=int32)

In [119]:
np.array(ri(10,100,45))

array([25, 24, 55, 32, 79, 11, 12, 15, 20, 85, 38, 84, 64, 70, 59, 77, 41,
       37, 55, 83, 82, 53, 31, 73, 36, 12, 56, 83, 72, 29, 22, 24, 35, 70,
       40, 36, 87, 73, 87, 78, 66, 95, 61, 20, 86])

In [120]:
import numpy as np
mat = np.array(ri(10,100,45)).reshape(3,5,3)
mat

array([[[87, 87, 80],
        [79, 52, 81],
        [83, 28, 78],
        [23, 55, 92],
        [11, 72, 21]],

       [[67, 59, 48],
        [13, 44, 38],
        [35, 81, 34],
        [74, 49, 77],
        [36, 81, 67]],

       [[26, 20, 58],
        [84, 93, 41],
        [94, 27, 16],
        [45, 80, 88],
        [20, 17, 43]]])

In [121]:
mat[1][1]

array([13, 44, 38])

In [122]:
mat[1][1][1]

44

Task

In [123]:
mat[0].T

array([[87, 79, 83, 23, 11],
       [87, 52, 28, 55, 72],
       [80, 81, 78, 92, 21]])

In [124]:
mat[0].T[1]

array([87, 52, 28, 55, 72])

In [126]:
# another methode for above task 
mat[0][:,1]

array([87, 52, 28, 55, 72])

In [127]:
mat[0][0:2,:]

array([[87, 87, 80],
       [79, 52, 81]])

In [128]:
mat[1][0:2,:]

array([[67, 59, 48],
       [13, 44, 38]])

In [129]:
mat[2][0:2,:]

array([[26, 20, 58],
       [84, 93, 41]])

In [130]:
mat[0:3,[0,1]]

array([[[87, 87, 80],
        [79, 52, 81]],

       [[67, 59, 48],
        [13, 44, 38]],

       [[26, 20, 58],
        [84, 93, 41]]])

In [131]:
for i in range(3):
    print(mat[i][:2,:])

[[87 87 80]
 [79 52 81]]
[[67 59 48]
 [13 44 38]]
[[26 20 58]
 [84 93 41]]


# Subseting

In [133]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[82, 47, 47, 89, 65],
       [18, 63, 72, 40, 54],
       [86, 12, 69, 25, 43]])

In [134]:
mat>40

array([[ True,  True,  True,  True,  True],
       [False,  True,  True, False,  True],
       [ True, False,  True, False,  True]])

In [135]:
mat[mat>40]

array([82, 47, 47, 89, 65, 63, 72, 54, 86, 69, 43])

# Universal Function 

In [136]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[1 3 5]
 [8 2 9]
 [8 3 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[6 3 1]
 [2 1 5]
 [9 5 1]]


In [139]:
mat1+mat2

array([[ 7,  6,  6],
       [10,  3, 14],
       [17,  8,  6]])

In [137]:
mat1 *mat2 # index wise multiplication not matrix

array([[ 6,  9,  5],
       [16,  2, 45],
       [72, 15,  5]])

In [138]:
# matrix mutiplication 
mat1@mat2

array([[ 57,  31,  21],
       [133,  71,  27],
       [ 99,  52,  28]])

In [140]:
mat1/0

C:\Users\LENOVO\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [141]:
1/0

ZeroDivisionError: division by zero

In [142]:
100 + mat1

array([[101, 103, 105],
       [108, 102, 109],
       [108, 103, 105]])

In [143]:
mat1**3

array([[  1,  27, 125],
       [512,   8, 729],
       [512,  27, 125]], dtype=int32)

In [144]:
pow(mat1,3)

array([[  1,  27, 125],
       [512,   8, 729],
       [512,  27, 125]], dtype=int32)

# Broadcasting

In [145]:
start = np.zeros((4,4))
start = start +100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [146]:
add_row = np.array([1,0,2,5])
add_row

array([1, 0, 2, 5])

In [151]:
y = start +add_row
y

array([[101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.],
       [101., 100., 102., 105.]])

In [156]:
add_cols = np.array([[1,2,3,4]])
add_cols = add_cols.T
add_cols

array([[1],
       [2],
       [3],
       [4]])

In [157]:
y = start+add_cols
y

array([[101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.],
       [104., 104., 104., 104.]])

# Maths

In [158]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print(mat1)
print(mat2)

[[7 7 7]
 [7 4 1]
 [1 1 7]]
[[7 6 6]
 [1 9 6]
 [6 9 8]]


In [159]:
np.sqrt(mat1)

array([[2.64575131, 2.64575131, 2.64575131],
       [2.64575131, 2.        , 1.        ],
       [1.        , 1.        , 2.64575131]])

In [160]:
np.exp(mat1)

array([[1096.63315843, 1096.63315843, 1096.63315843],
       [1096.63315843,   54.59815003,    2.71828183],
       [   2.71828183,    2.71828183, 1096.63315843]])

In [161]:
np.log10(mat1)

array([[0.84509804, 0.84509804, 0.84509804],
       [0.84509804, 0.60205999, 0.        ],
       [0.        , 0.        , 0.84509804]])

In [162]:
np.fmod(mat1, mat2)

array([[0, 1, 1],
       [0, 4, 1],
       [1, 1, 7]], dtype=int32)

In [163]:
a  =np.linspace(0,12*np.pi,1001)
a

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])